export const products = [
    {
        _id: '1',
        name: 'Airpods wireless bluetooth headphones',
        image: '/images/airpods.jpg',
        description:
            'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur dolores dolore eius alias delectus ad? At placeat tempora aliquid aut omnis, optio id ullam cum sequi nostrum vel eaque voluptas iure eius animi quasi eligendi veritatis excepturi aliquam, consectetur officiis vitae sunt? Mollitia officiis earum labore, porro in exercitationem incidunt',
        brand: 'Apple',
        category: 'Electronics',
        price: 88.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '2',
        name: 'Amazon echo dot 3rd Generation',
        image: '/images/alexa.jpg',
        description:
            'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur dolores dolore eius alias delectus ad? At placeat tempora aliquid aut omnis, optio id ullam cum sequi nostrum vel eaque voluptas iure eius animi quasi eligendi veritatis excepturi aliquam, consectetur officiis vitae sunt? Mollitia officiis earum labore, porro in exercitationem incidunt',
        brand: 'Amazon',
        category: 'Electronics',
        price: 100.99,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        _id: '3',
        name: 'Cannon eos 80d dslr camera',
        image: '/images/camera.jpg',
        description:
            'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur dolores dolore eius alias delectus ad? At placeat tempora aliquid aut omnis, optio id ullam cum sequi nostrum vel eaque voluptas iure eius animi quasi eligendi veritatis excepturi aliquam, consectetur officiis vitae sunt? Mollitia officiis earum labore, porro in exercitationem incidunt',
        brand: 'Apple',
        category: 'Electronics',
        price: 150.99,
        countInStock: 3,
        rating: 3.4,
        numReviews: 4,
    },
    {
        _id: '4',
        name: 'Logitech g-series gaming mouse',
        image: '/images/mouse.jpg',
        description:
            'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur dolores dolore eius alias delectus ad? At placeat tempora aliquid aut omnis, optio id ullam cum sequi nostrum vel eaque voluptas iure eius animi quasi eligendi veritatis excepturi aliquam, consectetur officiis vitae sunt? Mollitia officiis earum labore, porro in exercitationem incidunt',
        brand: 'Apple',
        category: 'Electronics',
        price: 15.99,
        countInStock: 3,
        rating: 5,
        numReviews: 4,
    },
    {
        _id: '5',
        name: 'iPhone 11 Pro Max 256GB memory',
        image: '/images/phone.jpg',
        description:
            'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur dolores dolore eius alias delectus ad? At placeat tempora aliquid aut omnis, optio id ullam cum sequi nostrum vel eaque voluptas iure eius animi quasi eligendi veritatis excepturi aliquam, consectetur officiis vitae sunt? Mollitia officiis earum labore, porro in exercitationem incidunt',
        brand: 'Apple',
        category: 'Electronics',
        price: 1000.99,
        countInStock: 3,
        rating: 2.6,
        numReviews: 4,
    },
    {
        _id: '6',
        name: 'Sony Playstation 5 Pro White version',
        image: '/images/playstation.jpg',
        description:
            'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur dolores dolore eius alias delectus ad? At placeat tempora aliquid aut omnis, optio id ullam cum sequi nostrum vel eaque voluptas iure eius animi quasi eligendi veritatis excepturi aliquam, consectetur officiis vitae sunt? Mollitia officiis earum labore, porro in exercitationem incidunt',
        brand: 'Sony',
        category: 'Electronics',
        price: 500.99,
        countInStock: 3,
        rating: 1.5,
        numReviews: 4,
    },
    {
        _id: '7',
        name:
            'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatem, ad',
        image: '/images/sample.jpg',
        description:
            'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur dolores dolore eius alias delectus ad? At placeat tempora aliquid aut omnis, optio id ullam cum sequi nostrum vel eaque voluptas iure eius animi quasi eligendi veritatis excepturi aliquam, consectetur officiis vitae sunt? Mollitia officiis earum labore, porro in exercitationem incidunt',
        brand: 'Sample',
        category: 'Electronics',
        price: 10.99,
        countInStock: 3,
        rating: 2.8,
        numReviews: 4,
    },
];
